description: |-
  The landing page provides links to the API definition
  (link relations `service-desc` and `service-doc`),
  and the Conformance declaration (path `/conformance`,
  link relation `conformance`).
content:
  application/json:
    schema:
      $ref: "bblocks://ogc.api.common.v1.schemas.landingPage"
  text/html:
    schema:
      type: string
